### ISSUE TITLE
product_sequence, unique code not working in odo10 enterprise

### ISSUE THREAD

**Issue by diezcode** [OCA/product-attribute#330] opened 2018-02-13 09:51 UTC
module: product_sequence
version: 10.0 enterprise

**Steps to reproduce**
Install Module
Uninstall Module

**Current behavior**
Can duplicate product and can save product with same default_code as other products.

**Expected behavior**
Should not let you save a product with an **existing default_code**

**Comment by ovnicraft** [comment] 2019-05-26 01:58
I cant reproduce your issue, tested with latest rev.

Longer time here, close it please.

**Closed as completed** 2019-05-26 09:09 UTC
